### ISSUE TITLE
No associated contract for context error

### ISSUE THREAD

**Issue by dmitriia** [nascentxyz/pyrometer#15]
Crashing when run on https://testnet.arbiscan.io/address/0x741654C43DC0562958E0b3c172F93f4bd54400F9#code (flat)

```md
pyrometer -vvvvv ./SubaccountFactory.sol 
thread 'main' panicked at 'No associated contract for context', /Users/d/dehat/src/pyrometer/shared/src/context/mod.rs:222:14
stack backtrace:
   0:        0x104bf3ebc - std::backtrace_rs::backtrace::libunwind::trace::h8787edacd429d828
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:        0x104bf3ebc - std::backtrace_rs::backtrace::trace_unsynchronized::h7a9846606490caa8
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:        0x104bf3ebc - std::sys_common::backtrace::_print_fmt::h95438bed72312512
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/sys_common/backtrace.rs:65:5
   3:        0x104bf3ebc - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h1027694b54c428d0
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/sys_common/backtrace.rs:44:22
   4:        0x104c09ed8 - core::fmt::write::hb60cc483d75d6594
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/fmt/mod.rs:1213:17
   5:        0x104bf18bc - std::io::Write::write_fmt::h6c907fc10bdb865b
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/io/mod.rs:1682:15
   6:        0x104bf3cd0 - std::sys_common::backtrace::_print::h323796fb767df5e0
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/sys_common/backtrace.rs:47:5
   7:        0x104bf3cd0 - std::sys_common::backtrace::print::h1a62458f14dd2797
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/sys_common/backtrace.rs:34:9
   8:        0x104bf532c - std::panicking::default_hook::{{closure}}::h03c6918072c36210
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panicking.rs:267:22
   9:        0x104bf5084 - std::panicking::default_hook::hd0f3cf66b6a0fb5e
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panicking.rs:286:9
  10:        0x104bf5950 - std::panicking::rust_panic_with_hook::h9ed2a7a45efbd034
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panicking.rs:688:13
  11:        0x104bf5770 - std::panicking::begin_panic_handler::{{closure}}::h535244d6186e3534
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panicking.rs:579:13
  12:        0x104bf4324 - std::sys_common::backtrace::__rust_end_short_backtrace::ha542aa49031c5cb5
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/sys_common/backtrace.rs:137:18
  13:        0x104bf54cc - rust_begin_unwind
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panicking.rs:575:5
  14:        0x104c17514 - core::panicking::panic_fmt::hc1e7b11add95109d
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/panicking.rs:64:14
  15:        0x104c08fe4 - core::panicking::panic_display::h4f6a6d9c90c2a577
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/panicking.rs:147:5
  16:        0x104c08fa8 - core::panicking::panic_str::h093e45861a4f3940
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/panicking.rs:131:5
  17:        0x104c174e0 - core::option::expect_failed::h13082a32d0e23cf7
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/option.rs:1924:5
  18:        0x104a9c198 - shared::context::ContextNode::associated_contract::h29c7bbbb1891bb7d
  19:        0x104a8ada8 - pyrometer::context::ContextBuilder::parse_ctx_expr::hb2cd7871a654ff4f
  20:        0x104a67428 - pyrometer::context::func::FuncCaller::intrinsic_func_call::hc4a69e758636217f
  21:        0x104a8b9e8 - pyrometer::context::ContextBuilder::parse_ctx_expr::hb2cd7871a654ff4f
  22:        0x104acf550 - <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter::h4212837b07f4a57f
  23:        0x104a8b814 - pyrometer::context::ContextBuilder::parse_ctx_expr::hb2cd7871a654ff4f
  24:        0x104a887c4 - pyrometer::context::ContextBuilder::parse_ctx_stmt_inner::he163909ed75e91b7
  25:        0x104a87ca8 - pyrometer::context::ContextBuilder::parse_ctx_stmt_inner::hd6e6110af1f15840
  26:        0x104a696d0 - pyrometer::context::func::FuncCaller::execute_call_inner::h8a3c5e3f2c0f97b2
  27:        0x104a68cd0 - pyrometer::context::func::FuncCaller::func_call_inner::h0603424edc9566cd
  28:        0x104a865dc - pyrometer::context::ContextBuilder::parse_ctx_stmt_inner::hbc500f51158ad4e5
  29:        0x104a8f948 - pyrometer::Analyzer::parse::h38ee9fc978d60b29
  30:        0x104a0b710 - pyrometer::main::h8ea434558af1757b
                               at /Users/d/dehat/src/pyrometer/cli/src/main.rs:119:42
  31:        0x104a4613c - core::ops::function::FnOnce::call_once::h095888031204766b
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/ops/function.rs:250:5
  32:        0x104a4613c - std::sys_common::backtrace::__rust_begin_short_backtrace::h020feb58b0580f9e
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/sys_common/backtrace.rs:121:18
  33:        0x1049fb2f0 - std::rt::lang_start::{{closure}}::h822ff7b8425f1b04
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/rt.rs:166:18
  34:        0x104beda68 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h602b6f29451c74c7
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/ops/function.rs:287:13
  35:        0x104beda68 - std::panicking::try::do_call::h8ad76c1527a3892b
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panicking.rs:483:40
  36:        0x104beda68 - std::panicking::try::hbfc990f7ac38d34c
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panicking.rs:447:19
  37:        0x104beda68 - std::panic::catch_unwind::h936bb5789e0b4241
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panic.rs:140:14
  38:        0x104beda68 - std::rt::lang_start_internal::{{closure}}::h896fa40a3ab062d0
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/rt.rs:148:48
  39:        0x104beda68 - std::panicking::try::do_call::h21fb8583a42bdaac
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panicking.rs:483:40
  40:        0x104beda68 - std::panicking::try::h90121103ee57470a
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panicking.rs:447:19
  41:        0x104beda68 - std::panic::catch_unwind::hfd5c7b5d06b8f149
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panic.rs:140:14
  42:        0x104beda68 - std::rt::lang_start_internal::h9f0566e553deb11e
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/rt.rs:148:20
  43:        0x104a10b78 - _main
```

**Comment by brockelmore** [comment]
Perfect bug report. Super helpful thanks. I’ll take a look tomorrow or monday.
