### ISSUE TITLE
.balance member access is unhandled

### ISSUE THREAD

**Issue by SergeKireev** [nascentxyz/pyrometer#24]
I have this when running on the $SAFEMOON contract:
https://bscscan.deth.net/address/0x8e7877fe58bc2a979692862df9e84e1bf7ec94ae
(contract is already flattened)
 
thread 'main' panicked at 'Unknown member access on address: "balance"', src/context/exprs/member_access.rs:576:30
stack backtrace:
   0: rust_begin_unwind
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:579:5
   1: core::panicking::panic_fmt
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/panicking.rs:64:14
   2: pyrometer::context::exprs::member_access::MemberAccess::builtin_member_access
   3: pyrometer::context::exprs::member_access::MemberAccess::member_access
   4: pyrometer::context::ContextBuilder::parse_ctx_expr
   5: pyrometer::context::exprs::require::Require::handle_require
   6: pyrometer::context::func_call::intrinsic_call::IntrinsicFuncCaller::intrinsic_func_call
   7: pyrometer::context::func_call::FuncCaller::fn_call_expr
   8: pyrometer::context::ContextBuilder::parse_ctx_expr
   9: pyrometer::context::ContextBuilder::parse_ctx_stmt_inner
  10: pyrometer::context::ContextBuilder::parse_ctx_stmt_inner
  11: pyrometer::context::func_call::FuncCaller::execute_call_inner
  12: pyrometer::context::func_call::FuncCaller::func_call_inner
  13: pyrometer::context::ContextBuilder::parse_ctx_stmt_inner
  14: pyrometer::Analyzer::final_pass
  15: pyrometer::Analyzer::parse
  16: pyrometer::main
             at /home/cergyketh/dev/evm/external/pyrometer/cli/src/main.rs:137:9
  17: core::ops::function::FnOnce::call_once
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/ops/function.rs:250:5

Maybe the native .balance access is not handled?

**Comment by brockelmore** [comment]
Thanks! This is supported in an upcoming PR, will close this issue when that merges (should be in a couple days)
