### ISSUE TITLE
show error for flatten contract

### ISSUE THREAD

**Issue by script-money** [nascentxyz/pyrometer#6]
```
thread 'main' panicked at 'not yet implemented', ~/pyrometer/src/lib.rs:382:30
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::panic
   3: pyrometer::Analyzer::parse_contract_def::{{closure}}
   4: <core::slice::iter::Iter<T> as core::iter::traits::iterator::Iterator>::for_each
             at /private/tmp/rust-20230210-6343-w92jca/rustc-1.67.1-src/library/core/src/slice/iter/macros.rs:211:21
   5: pyrometer::Analyzer::parse_contract_def
             at ~/pyrometer/src/lib.rs:352:9
   6: pyrometer::Analyzer::parse_source_unit_part
             at ~/pyrometer/src/lib.rs:259:37
   7: pyrometer::Analyzer::parse_source_unit::{{closure}}
             at ~/pyrometer/src/lib.rs:230:37
   8: core::iter::traits::iterator::Iterator::for_each::call::{{closure}}
             at /private/tmp/rust-20230210-6343-w92jca/rustc-1.67.1-src/library/core/src/iter/traits/iterator.rs:828:29
   9: <core::iter::adapters::enumerate::Enumerate<I> as core::iter::traits::iterator::Iterator>::fold::enumerate::{{closure}}
             at /private/tmp/rust-20230210-6343-w92jca/rustc-1.67.1-src/library/core/src/iter/adapters/enumerate.rs:106:27
  10: core::iter::traits::iterator::Iterator::fold
             at /private/tmp/rust-20230210-6343-w92jca/rustc-1.67.1-src/library/core/src/iter/traits/iterator.rs:2414:21
  11: <core::iter::adapters::enumerate::Enumerate<I> as core::iter::traits::iterator::Iterator>::fold
             at /private/tmp/rust-20230210-6343-w92jca/rustc-1.67.1-src/library/core/src/iter/adapters/enumerate.rs:112:9
  12: core::iter::traits::iterator::Iterator::for_each
             at /private/tmp/rust-20230210-6343-w92jca/rustc-1.67.1-src/library/core/src/iter/traits/iterator.rs:831:9
  13: pyrometer::Analyzer::parse_source_unit
             at ~/pyrometer/src/lib.rs:225:9
  14: pyrometer::Analyzer::parse
             at ~/pyrometer/src/lib.rs:189:29
  15: pyrometer::main
             at ~/pyrometer/cli/src/main.rs:119:42
  16: core::ops::function::FnOnce::call_once
             at /private/tmp/rust-20230210-6343-w92jca/rustc-1.67.1-src/library/core/src/ops/function.rs:507:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by brockelmore** [comment]
This should have been fixed in #9
